coverage:
  status:
    project:
      default:
        informational: true
        only_pulls: true
    patch:
      default:
        informational: true

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
